// <auto-generated />
using Measurement.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Measurement.WebApi.Migrations
{
    [DbContext(typeof(MeasurementWebApiContext))]
    [Migration("20220404221145_initMssql")]
    partial class initMssql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Measurement.WebApi.Models.SensorState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Measurement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "111"
                        },
                        new
                        {
                            Id = 2,
                            Value = "222"
                        },
                        new
                        {
                            Id = 3,
                            Value = "333"
                        },
                        new
                        {
                            Id = 4,
                            Value = "444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
